import type { Metadata } from 'next';
// fonts
import { Onest } from 'next/font/google';
// styles
import '../styles/globals.css';
import { ToastProvider } from '@/context/ToastContext';
import ToastContainer from '@/components/common/ToastContainer';

const onest = Onest({
  variable: '--font-onest',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  fallback: ['Arial', 'sans-serif'],
  preload: true,
  style: ['normal'],
});

export const metadata: Metadata = {
  title: 'Streamify',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} antialiased`}>
        <ToastProvider>
          {children}
          <ToastContainer />
        </ToastProvider>
      </body>
    </html>
  );
}
